### ISSUE TITLE
how do i even open it

### ISSUE THREAD

**Issue by kokoroko23** [KaylinOwO/Project-Apparatus#78]
i downloaded the zip file but idk what to do next

**Comment by realbillie** [comment]
> i downloaded the zip file but idk what to do next

Might want to google how to use sharpmonoinjector to inject .dll's into lethal company. Start there. Compiling in visual studio isn't really for beginners. You have to add references and fix up errors if there is any otherwise you can't compile. Maybe you should start with downloading someone's .dll for leather company and seeing how things work.

**Comment by kokoroko23** [comment]
> > i downloaded the zip file but idk what to do next
> 
> Might want to google how to use sharpmonoinjector to inject .dll's into lethal company. Start there. Compiling in visual studio isn't really for beginners. You have to add references and fix up errors if there is any otherwise you can't compile. Maybe you should start with downloading someone's .dll for lethal company and seeing how things work.

even so what .dll files should i put into lethal and where. do i put the whole thing or?

**Comment by kokoroko23** [comment]
cus i dont see any .dll files in the zip

**Comment by realbillie** [comment]
> cus i dont see any .dll files in the zip
> 
> 

This is GitHub where you share and fix code. Not a support chat for the cheat, please please check YouTube

How to use sharpmonoinjector with lethal company

**Comment by detectiveclea** [comment]
we got that just tell us where the .dll is
